#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.


a = 0
b = 1
soma = 0
resultado = 0

while soma <= 4000000:
    a = b
    b = soma
    parcial = soma
    if soma % 2 ==0:
        resultado += parcial
    soma = a + b

print "Resposta:" , resultado

